### ISSUE TITLE
Add `nimporter compile` CLI command

### ISSUE THREAD

**Issue by Pebaz** [Pebaz/nimporter#17]
Add a CLI command that will simplify the distribution of applications using Nimporter by lifting the requirement of using a `setup.py` for packaging.

### Todo

- [ ] `nimporter compile` CLI command
- [ ] Run `nimporter_cli.clean()` before building all modules/libraries
- [ ] Add documentation to README explaining use case behind the new command
- [ ] Add a hello-world example to `examples/` for using Nimporter with Docker
